gestao/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('criar_gerente/', views.criar_gerente, name="criar_gerente"),
    path('salvar_gerente/', views.salvar_gerente, name='salvar_gerente'),
    path('adm_estoque/', views.adm_estoque, name='adm_estoque'),
    path('detalhes_produto/<int:id>', views.detalhes_produto, name='detalhes_produto'),
    path('painel_controle/', views.painel_controle, name='painel_controle'),
    path('produtos_home/', views.produtos_home, name='produtos_home'),
    path('exibicao_home/', views.exibicao_home, name='exibicao_home'),
    path('gerenciar_banners/', views.gerenciar_banners, name='gerenciar_banners'),
    path('adicionar_banner/', views.adicionar_banner, name='adicionar_banner'),
    path('selecionar_banner/<int:id_banner>', views.selecionar_banner, name='selecionar_banner'),
    path('deletar_banner/<int:id_banner>', views.deletar_banner, name='deletar_banner'),
    path('tirar_banner_home/<int:id_banner>', views.tirar_banner_home, name='tirar_banner_home'),
    path('gerenciar_cupons/', views.gerenciar_cupons, name='gerenciar_cupons'),
    path('alterar_cupons/', views.alterar_cupons, name='alterar_cupons'),
    path('consultar_pedidos/', views.consultar_pedidos, name='consultar_pedidos'),
    
   
]

pytudo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as ckeditor_views
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('usuarios/', include('usuarios.urls')),
    path('produtos/', include('produtos.urls')),
    path('accounts/', include('allauth.urls')),
    path('gestao/', include('gestao.urls')),
    path('vendas/', include('vendas.urls')),
    path('checkout/', include('checkout.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

vendas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('adicionar_na_lista_desejo/<int:id>', views.adicionar_na_lista_desejo, name='adicionar_na_lista_desejo'),
    path('ver_lista_desejo/', views.ver_lista_desejo, name='ver_lista_desejo'),
    path('excluir_item_da_lista/<int:id_produto>/', views.excluir_item_da_lista, name='excluir_item_da_lista'),
    path('esvaziar_lista_desejo/', views.esvaziar_lista_desejo, name='esvaziar_lista_desejo'),
    path('carrinho/', views.carrinho, name='carrinho'),
    path('adicionar_ao_carrinho/<int:produto_id>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover_do_carrinho/<int:produto_id>/', views.remover_do_carrinho, name='remover_do_carrinho'),
    path('adicionar_quantidade_no_carrinho/', views.adicionar_quantidade_no_carrinho, name='adicionar_quantidade_no_carrinho'),
    path('excluir_do_carrinho/<int:id_produto>/', views.excluir_do_carrinho, name='excluir_do_carrinho'),
    path('criar_cupom/', views.criar_cupom, name='criar_cupom'),
    path('validar_cupom/', views.validar_cupom, name='validar_cupom'),
    path('retirar_cupom_da_session/', views.retirar_cupom_da_session, name='retirar_cupom_da_session'),
    
]

vendas/models.py
from django.db import models
from produtos.models import Produtos
from checkout.models import Pedido
from django.conf import settings

class ListaDesejo(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    produtos = models.ManyToManyField(Produtos, related_name="produtos", blank=True)

    def __str__(self):
        return str(self.usuario)

class CupomDesconto(models.Model):
    choices = (('P', 'Porcentagem'),('R', 'Reais'))
    codigo = models.CharField(max_length=50, unique=True)
    tipo_desconto = models.CharField(max_length=1, choices=choices)
    desconto = models.FloatField()
    quantidade = models.PositiveIntegerField()
    inicio_validade = models.DateField()
    fim_validade = models.DateField()
    criado_em = models.DateTimeField(auto_now_add=True)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.codigo
    
class HistoricoCupomDesconto(models.Model):
    venda = models.ForeignKey(Pedido, on_delete=models.SET_NULL, null=True)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.usuario.email} - {self.venda.id} - {self.data}"

vendas/forms.py
from dataclasses import fields
from django import forms
from .models import CupomDesconto

class FormCupomDesconto(forms.ModelForm):
    class Meta:
        model = CupomDesconto
        fields = '__all__'

vendas/views.py
from django.shortcuts import render, redirect
from produtos.models import Produtos
from vendas.models import ListaDesejo
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages import constants 
from rolepermissions.decorators import has_role_decorator
from django.contrib.auth.decorators import login_required
from .forms import FormCupomDesconto
from .models import CupomDesconto 
from datetime import date

@login_required
def adicionar_na_lista_desejo(request, id):
    lista_existente = ListaDesejo.objects.filter(usuario=request.user.id).first()
    produto = Produtos.objects.get(id=id)
    if lista_existente:
        lista_existente.produtos.add(produto) 
        return redirect(reverse('ver_lista_desejo'))
    else:
        lista = ListaDesejo(usuario_id=request.user.id) 
        lista.save()
        lista.produtos.add(produto)
        return redirect(reverse('ver_lista_desejo'))

@login_required
def ver_lista_desejo(request):
    lista = ListaDesejo.objects.filter(usuario_id=request.user.id).first()
    num_lista_desejo = 0
    if lista:
        num_lista_desejo = lista.produtos.count()
    return render(request, 'ver_lista_desejo.html', {'lista': lista, 'num_lista_desejo': num_lista_desejo})

@login_required
def excluir_item_da_lista(request, id_produto):
    lista = ListaDesejo.objects.get(usuario_id=request.user.id)
    produto = Produtos.objects.get(id=id_produto)
    lista.produtos.remove(produto)
    return redirect('ver_lista_desejo')

@login_required
def esvaziar_lista_desejo(request):
    try:
        lista = ListaDesejo.objects.get(usuario=request.user.id)
        lista.delete()
    except:
        messages.add_message(request, constants.ERROR, 'Erro ao deletar ou a lista já está vazia')
    return redirect(reverse('ver_lista_desejo'))

def adicionar_ao_carrinho(request, produto_id):
    if 'carrinho' not in request.session:
        request.session['carrinho'] = {}

    carrinho = request.session['carrinho']
    id_produto = str(produto_id)
    if id_produto in carrinho:
        carrinho[id_produto] += 1
    else:
        carrinho[id_produto] = 1
    request.session.modified = True

    return redirect('carrinho')

def remover_do_carrinho(request, produto_id):
    if 'carrinho' in request.session:
        carrinho = request.session['carrinho']
        id_produto = str(produto_id)
        if id_produto in carrinho:
            carrinho[id_produto] -= 1
            if carrinho[id_produto] <= 0:
                del carrinho[id_produto]
            request.session.modified = True

    return redirect('carrinho')

def carrinho(request):
    carrinho = []

    if 'carrinho' in request.session:
        carrinho_session = request.session['carrinho']
        carrinho_ids = list(carrinho_session.keys())
        carrinho = Produtos.objects.filter(id__in=carrinho_ids)
        soma_unidades = []
        for produto in carrinho:
            soma = produto.preco * carrinho_session[str(produto.id)]
            soma_unidades.append(soma)
        total = sum(soma_unidades)
        request.session['total'] = round(float(total), 2)
        request.session.modified = True
 
    if 'cupom' in request.session:
        cupom = request.session['cupom']
        valor_desconto = cupom['desconto'][0]
        tipo_desconto = cupom['desconto'][1]
        if tipo_desconto == 'R':
            total_com_desconto = float(total) - valor_desconto
            if total_com_desconto <= 0:
                total_com_desconto = 0
        elif tipo_desconto == 'P':
            total_com_desconto = round(float(total) - (float(total) * valor_desconto / 100),2)
            if total_com_desconto <= 0:
                total_com_desconto = 0
        request.session['total_com_desconto'] = round(float(total_com_desconto), 2)
        request.session.modified = True

    return render(request, 'carrinho.html', {'carrinho': carrinho})

def adicionar_quantidade_no_carrinho(request):
    carrinho = request.session['carrinho']
    for key, value in request.POST.items():
        if key.startswith('quantidade_') and value != '':
            replace = key.replace('quantidade_', '')
            carrinho[replace] = int(value)
            request.session.modified = True
    return redirect('carrinho')

def excluir_do_carrinho(request, id_produto):
    carrinho = request.session['carrinho']
    del carrinho[str(id_produto)]
    request.session.modified = True
    return redirect('carrinho')

@has_role_decorator('gerente')
def criar_cupom(request):
    if request.method == 'POST':
        form = FormCupomDesconto(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, constants.SUCCESS, 'Cupom criado com sucesso.')
            return redirect('gerenciar_cupons')
        else:
            messages.add_message(request, constants.ERROR, 'Não foi possível criar o cupom.')
    else:
        form = FormCupomDesconto()
    return render(request, 'criar_cupom.html', {'form': form})

def validar_cupom(request):
    codigo = request.POST.get('codigo')
    dia_atual = date.today()
    try:
        cupom = CupomDesconto.objects.get(codigo=codigo)
    except:
        messages.add_message(request, constants.ERROR, 'Cupom inválido.')
        return redirect('carrinho')
    if cupom.quantidade < 1:
        messages.add_message(request, constants.ERROR, 'Cupom esgotado.')
        return redirect('carrinho')
    if cupom.ativo == False:
        messages.add_message(request, constants.ERROR, 'Cupom desativado.')
        return redirect('carrinho')
    if cupom.inicio_validade > dia_atual:
        messages.add_message(request, constants.ERROR, 'Cupom fora da validade.')
        return redirect('carrinho')
    if dia_atual > cupom.fim_validade:
        messages.add_message(request, constants.ERROR, 'Cupom fora do prazo de validade.')
        return redirect('carrinho')
    
    request.session['cupom'] = {}
    desconto = request.session['cupom']
    desconto['desconto'] = [cupom.desconto, cupom.tipo_desconto, cupom.id]
    request.session.modified = True
    
    messages.add_message(request, constants.SUCCESS, f'Cupom {cupom.codigo} adicionado.')
    return redirect('carrinho')

def retirar_cupom_da_session(request):
    if 'cupom' in request.session:
        del request.session['cupom']
        request.session.modified = True
        messages.add_message(request, constants.SUCCESS, f'Cupom removido.')
    return redirect('carrinho')
    

vendas/templates/carrinho.html
{% extends 'base.html' %}
{% load static %}
{% load filtros %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'vendas/css/carrinho.css' %}" rel="stylesheet">
{% endblock %}


{% block 'body' %}     

{% if carrinho %}
<section class="h-100">
  <div class="container h-100 py-5">
    <div class="mb-3">
      <a href="{% url 'home' %}" class="custom-link"><i class="fa fa-arrow-left" aria-hidden="true"></i> Continuar comprando</a>
    </div>
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col" class="h5 text-center">Item</th>
                <th scope="col" class="text-center">Nome</th>
                <th scope="col">Quantidade</th>
                <th scope="col" class="text-center">Total</th>
                <th scope="col" class="text-center">Remover</th>
              </tr>
            </thead>
            <tbody>
              {% for produto in carrinho %}
              <tr>
                <th scope="row">
                  <div class=" imagem_carrinho d-flex justify-content-center align-items-center">
                      {% if produto.imagem_principal %}
                          <img src="{{produto.imagem_principal.url}}" alt="Imagem_produto">
                      {% else %}
                          <img src="{% static 'produtos\img\sem foto.jpg' %}" alt="Imagem_produto">
                      {% endif %}
                  </div>
                </th>

                <td class="align-middle text-center">
                  <div class="flex-column">
                      <p>{{ produto.nome }}</p>
                    </div>
                </td>
                
                <td class="align-middle text-center">
                  <div class="d-flex flex-row">
                    <a href="{% url 'remover_do_carrinho' produto.id %}">
                    <button class="btn btn-link px-2 me-1">
                      <i class="fas fa-minus"></i>
                    </button>
                  </a>

                    <form action="{% url 'adicionar_quantidade_no_carrinho'%}" method="POST" class="form-control form-control-sm p-0" style="width: 50px;"> {% csrf_token %} 
                      <input placeholder="{{request.session.carrinho|get_item:produto.id}}"  name="quantidade_{{produto.id}}" class="text-center h-100 w-100">
                    </form>

                      <a href="{% url 'adicionar_ao_carrinho' produto.id %}">
                    <button class="btn btn-link px-2 ms-1">
                      <i class="fas fa-plus"></i>
                    </button>
                  </a>
                  </div>
                </td>
 
                <td class="align-middle text-center">
                  <p class="mb-0" style="font-weight: 500;">R$ {{request.session.carrinho|get_item:produto.id|multiply_item:produto.preco}}</p>
                </td>

                <td class="align-middle text-center">
                  <a href="{% url 'excluir_do_carrinho' produto.id %}" class="lixeira"><i class="fas fa-trash fa-lg"></i></a>
                </td>
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>

          <div class="container d-flex mt-5 mb-5 justify-content-center">
            <form class="input-group" action="{% url 'validar_cupom' %}" method="POST" style="width: 70%;">{% csrf_token %}
              <div class = "input-group mb-3 mt-3">
                  <input type = "text" name="codigo" class = "form-control" placeholder="Cupom de desconto:">
                  <button class = "btn"  type = "submit"><i class = "fa fa-search"></i></button>
              </div>
            </form>
          </div>

          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="h5">Resumo</th>
                  <th scope="col" class="h5 align-middle text-end">Total</th>
                </tr>
              </thead>
              <tbody>
              <tr>
                <td class="align-middle">
                  <p class="mb-0" style="font-weight: 500;">{{request.session.carrinho|total_itens}} itens</p>
                </td>
                  <td class="align-middle text-end">
                    <p class="mb-0" style="font-weight: 500;">R$ {{request.session.total}}</p>
                  </td>
                </tr>

                {% if request.session.cupom %}
                  <tr>
                    <td class="align-middle">
                      <p class="mb-0" style="font-weight: 500;">Cupom de desconto 
                        <a href="{% url 'retirar_cupom_da_session'%}"><i class="fa fa-times-circle text-danger"></i></a>
                      </p>
                    </td>
                    <td class="align-middle text-end">
                        <p class="mb-0" style="font-weight: 500;">
                          {{request.session.cupom|get_cupom_type:'desconto'}} 
                        </p>
                    </td>
                  </tr>
                {% endif %}

                  <tr>
                    <td class="align-middle">
                      <p class="mb-0" style="font-weight: 500;">Frete</p>
                    </td>
                      <td class="align-middle text-end">
                        <p class="mb-0" style="font-weight: 500;">R$ frete</p>
                      </td>
                    </tr>

                    <tr>
                      <td class="align-middle">
                        <p class="mb-0" style="font-weight: 500;">TOTAL</p>
                      </td>
                      {% if request.session.cupom %}
                        <td class="align-middle text-end">
                          <p class="mb-0" style="font-weight: 500;">R$ {{request.session.total_com_desconto}}</p>
                        </td>
                        </tr>
                      {% else %}
                        <td class="align-middle text-end">
                          <p class="mb-0" style="font-weight: 500;">R$ {{request.session.total}}</p>
                        </td>
                        </tr>
                      {% endif%}
              </tbody>
            </table>
        </div>
      </div>
      <a class="btn mt-2" href="{% url 'checkout' %}" role="button">Finalizar a compra</a>
    </div>
  </div>
</section>
    
{% else %}
  <div class="container text-center my-5">
    <p>O carrinho está vazio.</p>
    <a class="btn mt-2" href="{% url 'home' %}" role="button">Começar as compras!</a>
  </div>
{% endif %}



{% endblock %}

vendas/templates/criar_cupom.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'produtos/css/listar_categorias.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

    <h2 class="titulo">Criar Cupom</h2>

    <form action="{% url 'criar_cupom' %}" method="POST">{% csrf_token %}
        <table>
            {{form.as_table}}
            {{ form.non_field_errors }}
        </table>
    <input class="btn btn-success" type="submit" value="Enviar">
    </form>
    

{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    
    <script> 
        $(document).ready(function(){
            $('#id_inicio_validade').mask('00/00/0000');
            $('#id_fim_validade').mask('00/00/0000');

        });

    </script>
{% endblock %}

vendas/templates/ver_carrinho.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'produtos/css/listar_produtos.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

    <div class="row">
        {% for produto in carrinho.produtos.all %}
            {{produto}}
        {% endfor %}
    </div>

    <br>
    <br>
    <br>
    <a class="btn btn-primary" href="{% url 'esvaziar_carrinho' %}" role="button">Esvaziar Carrinho</a>

{% endblock %}

vendas/templates/ver_lista_desejo.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'vendas/css/lista_desejo.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}
<div class="container-fluid d-sm-flex align-items-stretch px-0">
  {% include "menu_usuario.html" %}

  {% if lista.produtos.all %}
  <div class="container p-4">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" class="h5 text-center">Lista de Desejo</th>
            <th scope="col" class="text-center">Nome</th>
            <th scope="col" class="text-center">Preço</th>
            <th scope="col" class="text-center">Comprar</th>
            <th scope="col" class="text-center">Remover</th>
          </tr>
        </thead>
        <tbody>
          {% for produto in lista.produtos.all %}
          <tr>
            <th scope="row">
              <div class="imagem_carrinho d-flex justify-content-center align-items-center"> 
                  {% if produto.imagem_principal %}
                        <img src="{{produto.imagem_principal.url}}" alt="Imagem_produto">
                    {% else %}
                        <img src="{% static 'produtos\img\sem foto.jpg' %}" alt="Imagem_produto">
                    {% endif %}
              </div>
            </th>

            <td class="align-middle text-center">
              <div class="flex-column">
                  <p>{{ produto.nome }}</p>
                </div>
            </td>
            
            <td class="align-middle text-center">
              <p class="mb-0" style="font-weight: 500;">{{produto.preco}}</p>
            </td>

            <td class="align-middle text-center">
                <a href="{% url 'adicionar_ao_carrinho' produto.id %}" class="lixeira"><i class="fa fa-check fa-lg"></i></a>
            </td>

            <td class="align-middle text-center">
              <a href="{% url 'excluir_item_da_lista' produto.id %}" class="lixeira"><i class="fas fa-trash fa-lg"></i></a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="d-flex justify-content-center">
      <a class="btn mt-3" href="{% url 'esvaziar_lista_desejo' %}" role="button">Esvaziar Lista</a>
    </div>
  </div>
</div>
    
{% else %}
  <div class="container d-flex justify-content-center mt-5 mb-5">
    A lista de desejo está vazia.
  </div>
</div>
{% endif %}

{% endblock %} 