gestao/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('criar_gerente/', views.criar_gerente, name="criar_gerente"),
    path('salvar_gerente/', views.salvar_gerente, name='salvar_gerente'),
    path('adm_estoque/', views.adm_estoque, name='adm_estoque'),
    path('detalhes_produto/<int:id>', views.detalhes_produto, name='detalhes_produto'),
    path('painel_controle/', views.painel_controle, name='painel_controle'),
    path('produtos_home/', views.produtos_home, name='produtos_home'),
    path('exibicao_home/', views.exibicao_home, name='exibicao_home'),
    path('gerenciar_banners/', views.gerenciar_banners, name='gerenciar_banners'),
    path('adicionar_banner/', views.adicionar_banner, name='adicionar_banner'),
    path('selecionar_banner/<int:id_banner>', views.selecionar_banner, name='selecionar_banner'),
    path('deletar_banner/<int:id_banner>', views.deletar_banner, name='deletar_banner'),
    path('tirar_banner_home/<int:id_banner>', views.tirar_banner_home, name='tirar_banner_home'),
    path('gerenciar_cupons/', views.gerenciar_cupons, name='gerenciar_cupons'),
    path('alterar_cupons/', views.alterar_cupons, name='alterar_cupons'),
    path('consultar_pedidos/', views.consultar_pedidos, name='consultar_pedidos'),
    
   
]

pytudo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as ckeditor_views
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('usuarios/', include('usuarios.urls')),
    path('produtos/', include('produtos.urls')),
    path('accounts/', include('allauth.urls')),
    path('gestao/', include('gestao.urls')),
    path('vendas/', include('vendas.urls')),
    path('checkout/', include('checkout.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

gestao/models.py
from django.db import models

class Banner(models.Model):
    imagem = models.ImageField(upload_to ='banners/')
    home = models.BooleanField(default=False)
    titulo = models.CharField(max_length=50, blank=True, null=True)
    subtitulo = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f"{self.imagem}"

vendas/models.py
from django.db import models
from produtos.models import Produtos
from checkout.models import Pedido
from django.conf import settings

class ListaDesejo(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    produtos = models.ManyToManyField(Produtos, related_name="produtos", blank=True)

    def __str__(self):
        return str(self.usuario)

class CupomDesconto(models.Model):
    choices = (('P', 'Porcentagem'),('R', 'Reais'))
    codigo = models.CharField(max_length=50, unique=True)
    tipo_desconto = models.CharField(max_length=1, choices=choices)
    desconto = models.FloatField()
    quantidade = models.PositiveIntegerField()
    inicio_validade = models.DateField()
    fim_validade = models.DateField()
    criado_em = models.DateTimeField(auto_now_add=True)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.codigo
    
class HistoricoCupomDesconto(models.Model):
    venda = models.ForeignKey(Pedido, on_delete=models.SET_NULL, null=True)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.usuario.email} - {self.venda.id} - {self.data}"

gestao/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.messages import constants 
from rolepermissions.roles import assign_role
from django.contrib.auth.models import User
from rolepermissions.decorators import has_role_decorator
from produtos.models import Produtos, Categoria, DestacadosHome
from django.core.paginator import Paginator
from decimal import Decimal
from .models import Banner
from vendas.models import CupomDesconto
from checkout.models import Pedido
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator
from django.contrib.auth.password_validation import validate_password

@login_required
def criar_gerente(request):
    if request.user.is_superuser:
        return render(request, 'criar_gerente.html')
    else:
        messages.add_message(request, constants.ERROR, 'Você não tem permissão para executar essa função.')
        return redirect('home')

@login_required
def salvar_gerente(request):
    if request.user.is_superuser:
        email = request.POST.get('email')
        senha_provisoria = request.POST.get('senha_provisoria')
        senha_provisoria2 = request.POST.get('senha_provisoria2')

        if validar_formulario_gerente(request, email, senha_provisoria, senha_provisoria2):
            gerente = User.objects.create_user(username=email,
                                        email=email,
                                        password=senha_provisoria)
            assign_role(gerente, 'gerente')
            messages.add_message(request, constants.SUCCESS, 'Gerente cadastrado com sucesso')
            return redirect('home')
        else:
            return redirect('criar_gerente')
    else:
        messages.add_message(request, constants.ERROR, 'Você não tem permissão para executar essa função.')
        return redirect('home')

@has_role_decorator('gerente')
def adm_estoque(request):
    produtos = Produtos.objects.all()
    categorias = Categoria.objects.all()

    nome_filtrar = request.GET.get('nome')
    if nome_filtrar:
        produtos = produtos.filter(nome__icontains=nome_filtrar)
     
    categoria_filtrar = request.GET.get('categoria')
    if categoria_filtrar: 
        produtos = produtos.filter(categoria_id=categoria_filtrar)
    
    preco_menor_filtrar = request.GET.get('preco_menor_filtrar')
    if preco_menor_filtrar:
        preco_menor_filtrar_decimal = Decimal(preco_menor_filtrar.replace(',','.'))
        produtos = produtos.filter(preco__lt=preco_menor_filtrar_decimal)
    
    preco_maior_filtrar = request.GET.get('preco_maior_filtrar')
    if preco_maior_filtrar:
        preco_maior_filtrar_decimal = Decimal(preco_maior_filtrar.replace(',','.'))
        produtos = produtos.filter(preco__gt=preco_maior_filtrar_decimal)

    preco_de_custo_menor_filtrar = request.GET.get('preco_de_custo_menor_filtrar')
    if preco_de_custo_menor_filtrar:
        preco_de_custo_menor_filtrar_decimal = Decimal(preco_de_custo_menor_filtrar.replace(',','.'))
        produtos = produtos.filter(preco_de_custo__lt=preco_de_custo_menor_filtrar_decimal)
    
    preco_de_custo_maior_filtrar = request.GET.get('preco_de_custo_maior_filtrar')
    if preco_de_custo_maior_filtrar:
        preco_de_custo_maior_filtrar_decimal = Decimal(preco_de_custo_maior_filtrar.replace(',','.'))
        produtos = produtos.filter(preco_de_custo__gt=preco_de_custo_maior_filtrar_decimal)

    marca_filtar = request.GET.get('marca')
    if marca_filtar:
        produtos = produtos.filter(marca__icontains=marca_filtar)

    cor_filtar = request.GET.get('cor')
    if cor_filtar:
        produtos = produtos.filter(cor__icontains=cor_filtar)

    quantidade_menor_filtrar = request.GET.get('quantidade_menor_filtrar')
    if quantidade_menor_filtrar:
        produtos = produtos.filter(quantidade__lt=quantidade_menor_filtrar)

    quantidade_maior_filtrar = request.GET.get('quantidade_maior_filtrar')
    if quantidade_maior_filtrar:
        produtos = produtos.filter(quantidade__gt=quantidade_maior_filtrar)


    produtos_ordenados = produtos.order_by('-id')
    paginacao = Paginator(produtos_ordenados, 8)
    page = request.GET.get('page')
    produtos_paginados = paginacao.get_page(page)

    return render(request, 'adm_estoque.html', {'produtos_paginados': produtos_paginados,
                                                'categorias': categorias})

@has_role_decorator('gerente')
def detalhes_produto(request, id):
    produto = Produtos.objects.get(id=id)
    return render(request, 'detalhes_produto.html', {'produto': produto})

@has_role_decorator('gerente')
def painel_controle(request):
    return render(request, 'painel_controle.html')

@has_role_decorator('gerente')
def produtos_home(request):
    produtos = Produtos.objects.all()
    categorias = Categoria.objects.all()
    nome_filtrar = request.GET.get('nome')
    if nome_filtrar:
        produtos = produtos.filter(nome__icontains=nome_filtrar)
     
    categoria_filtrar = request.GET.get('categoria')
    if categoria_filtrar: 
        produtos = produtos.filter(categoria_id=categoria_filtrar)
    
    preco_menor_filtrar = request.GET.get('preco_menor_filtrar')
    if preco_menor_filtrar:
        preco_menor_filtrar_decimal = Decimal(preco_menor_filtrar.replace(',','.'))
        produtos = produtos.filter(preco__lt=preco_menor_filtrar_decimal)
    
    preco_maior_filtrar = request.GET.get('preco_maior_filtrar')
    if preco_maior_filtrar:
        preco_maior_filtrar_decimal = Decimal(preco_maior_filtrar.replace(',','.'))
        produtos = produtos.filter(preco__gt=preco_maior_filtrar_decimal)

    preco_de_custo_menor_filtrar = request.GET.get('preco_de_custo_menor_filtrar')
    if preco_de_custo_menor_filtrar:
        preco_de_custo_menor_filtrar_decimal = Decimal(preco_de_custo_menor_filtrar.replace(',','.'))
        produtos = produtos.filter(preco_de_custo__lt=preco_de_custo_menor_filtrar_decimal)
    
    preco_de_custo_maior_filtrar = request.GET.get('preco_de_custo_maior_filtrar')
    if preco_de_custo_maior_filtrar:
        preco_de_custo_maior_filtrar_decimal = Decimal(preco_de_custo_maior_filtrar.replace(',','.'))
        produtos = produtos.filter(preco_de_custo__gt=preco_de_custo_maior_filtrar_decimal)

    marca_filtar = request.GET.get('marca')
    if marca_filtar:
        produtos = produtos.filter(marca__icontains=marca_filtar)

    cor_filtar = request.GET.get('cor')
    if cor_filtar:
        produtos = produtos.filter(cor__icontains=cor_filtar)

    quantidade_menor_filtrar = request.GET.get('quantidade_menor_filtrar')
    if quantidade_menor_filtrar:
        produtos = produtos.filter(quantidade__lt=quantidade_menor_filtrar)

    quantidade_maior_filtrar = request.GET.get('quantidade_maior_filtrar')
    if quantidade_maior_filtrar:
        produtos = produtos.filter(quantidade__gt=quantidade_maior_filtrar)


    produtos_ordenados = produtos.order_by('-id')
    paginacao = Paginator(produtos_ordenados, 10)
    page = request.GET.get('page')
    produtos_paginados = paginacao.get_page(page)
    return render(request, 'produtos_home.html', {'produtos_paginados': produtos_paginados,
                                                  'categorias': categorias}) 

@has_role_decorator('gerente')
def exibicao_home(request):
    produtos = request.POST.getlist('selecionados[]')
    acao = request.POST.get('acao')
    if produtos == []:
        messages.add_message(request, constants.ERROR, 'Selecione um produto')
        return redirect('/gestao/produtos_home')

    if acao == 'incluir':
        try:
            for produto in produtos:
                if DestacadosHome.objects.filter(produto_id=produto).exists() == False:
                    home = DestacadosHome(produto_id=produto) 
                    home.save()
            messages.add_message(request, constants.SUCCESS, 'Produtos adicionados na home com sucesso')
        except:
            messages.add_message(request, constants.ERROR, 'Erro ao adicionar produtos. Tente novamente mais tarde')

    if acao == 'excluir':
        try:
            for produto in produtos:
                home = DestacadosHome.objects.filter(produto_id=produto)
                for obj in home:
                    obj.delete()
            messages.add_message(request, constants.SUCCESS, 'Produtos deletados da home com sucesso')
        except:
            messages.add_message(request, constants.ERROR, 'Erro ao deletar produtos. Tente novamente mais tarde')

    return redirect('/gestao/produtos_home')

@has_role_decorator('gerente')
def gerenciar_banners(request):
    banners = Banner.objects.all()
    return render(request, 'gerenciar_banners.html', {'banners': banners})

@has_role_decorator('gerente')
def adicionar_banner(request):
    img = request.FILES.get('banner')
    titulo = request.POST.get('titulo')
    subtitulo = request.POST.get('subtitulo')
    if img:
        banner = Banner(imagem=img, titulo=titulo, subtitulo=subtitulo)
        banner.save()
        messages.add_message(request, constants.SUCCESS, 'Banner salvo com sucesso')
        return redirect('/gestao/gerenciar_banners')
    else:
        messages.add_message(request, constants.ERROR, 'Selecione uma imagem válida')
        return redirect('/gestao/gerenciar_banners')

@has_role_decorator('gerente')
def selecionar_banner(request, id_banner):
    banner = Banner.objects.get(id=id_banner)
    banner.home = True
    banner.save()
    messages.add_message(request, constants.SUCCESS, 'Banner adicionado na home com sucesso.')
    return redirect('/gestao/gerenciar_banners')

@has_role_decorator('gerente')
def deletar_banner(request, id_banner):
    banner = Banner.objects.get(id=id_banner)
    banner.delete()
    messages.add_message(request, constants.SUCCESS, 'Banner deletado com sucesso')
    return redirect('/gestao/gerenciar_banners')

@has_role_decorator('gerente')

gestao/templates/adm_estoque.html
{% extends 'base.html' %}
{% load static %}
{% load filtros %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="#" rel="stylesheet">
{% endblock %}

{% block 'body' %}

    <form action="#" method="GET"> {% csrf_token %} 
        <div class="row">
            
                <div class="col-md-5">
                    <input type="text" placeholder="Busque pelo nome" class="form-control" name="nome">
                </div>

                <div class="col-md-4">
                    <select class="form-select" name="categoria">
                        <option value="" disabled selected hidden>Escolha uma categoria</option>
                        {% for categoria in categorias %}
                            <option value="{{categoria.id}}">{{categoria}} </option>
                        {% endfor %}
                    </select>
                </div>

                <div>
                    <label>Preço menor que:</label>
                    <input type="text" id="preco_menor_filtrar" name="preco_menor_filtrar">

                    <label> Preço maior que:</label>
                    <input type="text" id="preco_maior_filtrar" name="preco_maior_filtrar">
                </div>

                <div>
                    <label>Preço de custo menor que:</label>
                    <input type="text" id="preco_de_custo_menor_filtrar" name="preco_de_custo_menor_filtrar">

                    <label> Preço de custo maior que:</label>
                    <input type="text" id="preco_de_custo_maior_filtrar" name="preco_de_custo_maior_filtrar">
                </div>

                <input type="text" placeholder="Busque pela marca"  name="marca">

                <input type="text" placeholder="Busque pela cor"  name="cor">

                <div>
                    <label> Quantidade menor que:</label>
                    <input type="text" name="quantidade_menor_filtrar">

                    <label> Quantidade maior que:</label>
                    <input type="text" name="quantidade_maior_filtrar">
                </div>
            
            <div class="col-md-3">
                <input type="submit" value="FILTRAR" class="btn btn-primary">
            </div>
        </div>
    </form>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Foto</th>
        <th scope="col">Nome</th>
        <th scope="col">Categoria</th>
        <th scope="col"> Quantidade</th>
        <th scope="col"> Marca</th>
        <th scope="col"> Cor</th>
        <th scope="col"> Preço de custo</th>
        <th scope="col"> Preço</th>
        <th scope="col">Editar</th>
        <th scope="col">Remover</th>
      </tr>
    </thead>

    <tbody>
        {% for produto in produtos_paginados %}
            <tr>
                <th scope="row">{{ produto.id }}</th>
                <td><a href="{% url 'detalhes_produto' produto.id %}">
                        {% if produto.imagem_principal %}
                            <img src="{{produto.imagem_principal.url}}" width="80" height="80"></td>
                        {% else %}
                            <img src="{% static 'produtos\img\sem foto.jpg' %}" width="80" height="80"></td>
                        {% endif %}
                    </a>
                <td>{{ produto.nome}}</td>
                {% if produto.categoria %}
                    <td>{{ produto.categoria}}</td>
                {% else %}
                    <td>Sem categoria </td>
                {% endif %}
                <td>{{ produto.quantidade}}</td> 
                <td>{{ produto.marca}}</td>
                <td>{{ produto.cor}}</td>
                <td>{{ produto.preco_de_custo}}</td>
                <td>{{ produto.preco}}</td>
                <td><a href="{% url 'alterar_produto' produto.id %}">Alterar</a></td>
                <td><a href="{% url 'excluir_produto' produto.id %}">Remover</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="pagination">
    {% if produtos_paginados.has_previous %}
        <a href="?{% param_replace page=1 %}">First</a>
        {% if produtos_paginados.previous_page_number != 1 %}
            <a href="?{% param_replace page=produtos_paginados.previous_page_number %}">Previous</a>
        {% endif %}
    {% endif %}

    Page {{ produtos_paginados.number }} of {{ paginator.num_pages }} 

    {% if produtos_paginados.has_next %}
        {% if produtos_paginados.next_page_number != paginator.num_pages %}
            <a href="?{% param_replace page=produtos_paginados.next_page_number %}">Next</a>
        {% endif %}
        <a href="?{% param_replace page=paginator.num_pages %}">Last</a>
    {% endif %}

    <p>Objects {{ produtos_paginados.start_index }}—{{ produtos_paginados.end_index }}</p>
    
</div> 

{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    
    <script> 
        $(document).ready(function(){
          $('#preco_menor_filtrar').mask('000000,00', {reverse: true});
          $('#preco_maior_filtrar').mask('000000,00', {reverse: true});
          $('#preco_de_custo_menor_filtrar').mask('000000,00', {reverse: true});
          $('#preco_de_custo_maior_filtrar').mask('000000,00', {reverse: true});


        });

    </script>
{% endblock %}

gestao/templates/consultar_pedidos.html
{% extends 'base.html' %}
{% load static %}
{% load filtros %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'gestao/css/consultar_pedidos.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<div class="container-fluid d-sm-flex align-items-stretch px-0">
    {% include "menu_gerente.html" %}
  
    <div class="container px-5 py-4">
        <div class="text-center mt-1">
            <h2>Consultar Pedidos</h2>
        </div>

        <div class="m-3 d-flex justify-content-center text-center">
        <form action="#" method="GET" class="w-50"> {% csrf_token %} 
            <input type="number" placeholder="Numero do Pedido" class="form-control" name="numero">
            <input type="submit" value="BUSCAR" class="btn m-2">
        </form>
        </div>

        <div class="table-responsive">
            <table class="table table-striped border">
            <thead>
                <tr>
                <th scope="col">Número</th>
                <th scope="col">Data</th>
                <th scope="col">Valor</th>
                <th scope="col">Pagamento</th>
                <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
            {% for pedido in pedidos %}
                <tr onclick="window.location='{% url 'ver_pedido' pedido.id %}'" style="cursor: pointer;">
                <td>{{pedido.id}}</td>
                <td>{{pedido.data_pedido|date:"d/m/Y"}}</td>
                <td>{{pedido.valor_total}}</td>
                <td>{{pedido.metodo_de_pagamento}}</td>
                <td>{{pedido.status}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>

        <div class="pagination">
            {% if pedidos.has_previous %}
            <a class="pagination-action" href="?{% param_replace page=1 %}">
                <i class='fa fa-angle-double-left' aria-hidden="true"></i> </a>
            <a class="pagination-action" href="?{% param_replace page=pedidos.previous_page_number %}">
                <i class='fa fa-arrow-left' aria-hidden="true"></i>
            </a>
            {% endif %}
            {% for num in pedidos.paginator.page_range %}
                {% if pedidos.number == num %}
                    <span class="pagination-number pagination-current">{{ num }}</span>
                {% elif num > pedidos.number|add:'-3' and num < pedidos.number|add:'3' %}
                    <a class="pagination-number" href="?{% param_replace page=num %}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if pedidos.has_next %}
                <a class="pagination-action" href="?{% param_replace page=pedidos.next_page_number %}">
                    <i class='fa fa-arrow-right' aria-hidden="true"></i>
                </a>
                <a class="pagination-action" href="?{% param_replace page=pedidos.paginator.num_pages %}" >        
                    <i class='fa fa-angle-double-right' aria-hidden="true"></i>
                </a>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %} 

gestao/templates/criar_gerente.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'gestao/css/criar_gerente.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<div class="container-fluid d-sm-flex align-items-stretch px-0">
    {% include "menu_gerente.html" %}
  
    <div class="container px-5 py-4">
        <div class="text-center mt-1">
            <h2>Criar Gerente</h2>
        </div>

        <div class="d-flex justify-content-center">
            <form action="{% url 'salvar_gerente' %}" method="POST" class="form-control w-50"> {%csrf_token%}
                <label>Email:</label>
                <input type="email" class="form-control mb-2" name="email">
        
                <label>Senha provisória:</label>
                <input type="password" class="form-control mb-2" name="senha_provisoria" placeholder="Digite a senha provisória">
        
                <label>Repita a senha novamente:</label>
                <input type="password" class="form-control mb-2" name="senha_provisoria2" placeholder="Digite a senha provisória">
                <div class="d-flex justify-content-center">
                    <input type="submit" value="CADASTRAR" class="btn">
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock %}

gestao/templates/gerenciar_cupons.html
{% extends 'base.html' %}
{% load static %}
{% load filtros %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'produtos/css/listar_produtos.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<a class="btn btn-primary" href="{% url 'criar_cupom' %}" role="button">Criar novo cupom</a>

<form action="#" method="GET"> {% csrf_token %} 
    <div class="row">
        
        <div class="col-md-5">
            <input type="text" placeholder="Busque pelo nome" class="form-control" name="nome">
        </div>

        <div class="col-md-3">
            <input type="submit" value="FILTRAR" class="btn btn-primary">
        </div>
    </div>
</form>

<form action="{% url 'alterar_cupons' %}" method="POST"> {% csrf_token %}

    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Selecionar</th> 
            <th scope="col">Codigo</th>
            <th scope="col">Tipo de Desconto</th>
            <th scope="col">Desconto</th>
            <th scope="col">Quantidade</th>
            <th scope="col">Início</th>
            <th scope="col">Fim</th>
            <th scope="col">Criado em</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
    
        <tbody>
            {% for cupom in cupons_paginados %}
                <tr>
                    <td><input type="checkbox" name="selecionados[]" value="{{ cupom.id }}"></td> 
                    <td>{{ cupom.codigo}}</td>
                    <td>{{ cupom.get_tipo_desconto_display}}</td>
                    <td>{{ cupom.desconto}}</td> 
                    <td>{{ cupom.quantidade}}</td>
                    <td>{{ cupom.inicio_validade|date:"d/m/Y"}}</td>
                    <td>{{ cupom.fim_validade|date:"d/m/Y"}}</td>
                    <td>{{ cupom.criado_em|date:"d/m/Y"}}</td>
                    <td>{% if cupom.ativo %}
                            Ativo
                        {% else %}
                            Desabilitado
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <label for="acao">Selecione uma ação:</label>
    <select name="acao" id="acao">
    <option value="ativar">Ativar Cupom</option>
    <option value="desabilitar">Desabilitar Cupom</option>
    <option value="excluir">Excluir Cupom</option>
    </select>
      
    <input type="submit" value="Alterar">
    </form> 

    <div class="pagination">
        {% if cupons_paginados.has_previous %}
            <a href="?{% param_replace page=1 %}">First</a>
            {% if cupons_paginados.previous_page_number != 1 %}
                <a href="?{% param_replace page=cupons_paginados.previous_page_number %}">Previous</a>
            {% endif %}
        {% endif %}
    
        Page {{ cupons_paginados.number }} of {{ paginator.num_pages }} 
    
        {% if cupons_paginados.has_next %}
            {% if cupons_paginados.next_page_number != paginator.num_pages %}
                <a href="?{% param_replace page=cupons_paginados.next_page_number %}">Next</a>
            {% endif %}
            <a href="?{% param_replace page=paginator.num_pages %}">Last</a>
        {% endif %}
    
        <p>Objects {{ cupons_paginados.start_index }}—{{ cupons_paginados.end_index }}</p>
        
    </div> 
    
    
{% endblock %}

gestao/templates/painel_controle.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'usuarios/css/perfil_usuario.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<div class="container-fluid d-sm-flex align-items-stretch px-0">
    {% include "menu_gerente.html" %}
  
    <div class="container px-5 py-4">
        <div class="text-center mt-1">
            <h2>Painel de Controle</h2>
        </div>
    </div>

</div>


{% endblock %} 