gestao/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('criar_gerente/', views.criar_gerente, name="criar_gerente"),
    path('salvar_gerente/', views.salvar_gerente, name='salvar_gerente'),
    path('adm_estoque/', views.adm_estoque, name='adm_estoque'),
    path('detalhes_produto/<int:id>', views.detalhes_produto, name='detalhes_produto'),
    path('painel_controle/', views.painel_controle, name='painel_controle'),
    path('produtos_home/', views.produtos_home, name='produtos_home'),
    path('exibicao_home/', views.exibicao_home, name='exibicao_home'),
    path('gerenciar_banners/', views.gerenciar_banners, name='gerenciar_banners'),
    path('adicionar_banner/', views.adicionar_banner, name='adicionar_banner'),
    path('selecionar_banner/<int:id_banner>', views.selecionar_banner, name='selecionar_banner'),
    path('deletar_banner/<int:id_banner>', views.deletar_banner, name='deletar_banner'),
    path('tirar_banner_home/<int:id_banner>', views.tirar_banner_home, name='tirar_banner_home'),
    path('gerenciar_cupons/', views.gerenciar_cupons, name='gerenciar_cupons'),
    path('alterar_cupons/', views.alterar_cupons, name='alterar_cupons'),
    path('consultar_pedidos/', views.consultar_pedidos, name='consultar_pedidos'),
    
   
]

produtos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('listar_produtos/', views.listar_produtos, name="listar_produtos"),
    path('cadastrar_produto/', views.cadastrar_produto, name='cadastrar_produto'),
    path('ver_produto/<int:id>', views.ver_produto, name='ver_produto'),
    path('excluir_produto/<int:id>', views.excluir_produto, name='excluir_produto'),
    path('listar_categorias', views.listar_categorias, name='listar_categorias'),
    path('cadastrar_categoria', views.cadastrar_categoria, name='cadastrar_categoria'),
    path('excluir_categoria/<int:id>', views.excluir_categoria, name='excluir_categoria'),
    path('alterar_produto/<int:id>', views.alterar_produto, name='alterar_produto'),
    path('salvar_avaliacao/<int:id_produto>', views.salvar_avaliacao, name='salvar_avaliacao'),
    path('alterar_imagem_principal/<int:id_produto>', views.alterar_imagem_principal, name='alterar_imagem_principal'),
    path('incluir_imagens/<int:id_produto>', views.incluir_imagens, name='incluir_imagens'),
    path('excluir_imagem/<int:id_imagem>/<int:id_produto>', views.excluir_imagem, name='excluir_imagem'),
    path('excluir_imagem_principal/<int:id_produto>', views.excluir_imagem_principal, name='excluir_imagem_principal'),
    path('excluir_avaliacao/<int:id_avaliacao>/<int:id_produto>', views.excluir_avaliacao, name='excluir_avaliacao'),
    path('atualizar_especificacao/<int:id>', views.atualizar_especificacao, name='atualizar_especificacao'),
    path('calcular_frete_produto/<int:id_produto>', views.calcular_frete_produto, name='calcular_frete_produto'),
    path('teste/', views.teste, name='teste'),
]

pytudo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as ckeditor_views
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('usuarios/', include('usuarios.urls')),
    path('produtos/', include('produtos.urls')),
    path('accounts/', include('allauth.urls')),
    path('gestao/', include('gestao.urls')),
    path('vendas/', include('vendas.urls')),
    path('checkout/', include('checkout.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

produtos/models.py
from typing import Any, Dict, Tuple
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from usuarios.models import Usuarios
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField

class Categoria(models.Model):
    nome = models.CharField(max_length=40)

    def __str__(self):
        return self.nome

class Produtos(models.Model):
    nome = models.CharField(max_length=40)
    descricao = models.TextField(blank=True, null=True)
    preco_de_custo = models.DecimalField(max_digits=8, decimal_places=2)
    preco = models.DecimalField(max_digits=8, decimal_places=2)
    categoria = models.ForeignKey(Categoria, blank=True, null=True, on_delete=models.SET_NULL)
    marca = models.CharField(max_length=50, blank=True, null=True)
    cor = models.CharField(max_length=30, blank=True, null=True)
    quantidade = models.IntegerField()
    data_cadastro = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True, null=True)
    imagem_principal = models.ImageField(upload_to ='produtos/', blank=True, null=True)
    especificacao = RichTextUploadingField(blank=True, null=True)
    frete_gratis = models.BooleanField(default=False)
    altura = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    largura = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    profundidade = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    peso = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)


    def __str__(self):
        return self.nome
    
    def delete(self, *args, **kwargs):
        registro = RegistroAlteracaoProduto(
            produto=self,
            detalhes=f'Produto {self.nome} excluído.',
        )
        registro.save()
        super().delete(*args, **kwargs)
        
    
    def save(self, *args, **kwargs):
        if self.data_cadastro != self.data_atualizacao:
            old_obj = Produtos.objects.get(pk=self.pk)
            old_nome = old_obj.nome
            old_descricao = old_obj.descricao
            old_preco_de_custo = old_obj.preco_de_custo
            old_preco = old_obj.preco
            old_categoria = old_obj.categoria
            old_marca = old_obj.marca
            old_cor = old_obj.cor
            old_quantidade = old_obj.quantidade
            old_imagem_principal = old_obj.imagem_principal
            old_especificacao = old_obj.especificacao
            detalhes = f"Produto atualizado - {self.comparar_alteracoes(old_nome, old_descricao, old_preco_de_custo, old_preco, old_categoria, old_marca, old_cor, old_quantidade, old_imagem_principal, old_especificacao)}"
        else:
            detalhes = f"Produto {self.nome} criado"

        super().save(*args, **kwargs)
            
        registro = RegistroAlteracaoProduto(
            produto=self,
            detalhes=detalhes,
        )
        registro.save()

    def comparar_alteracoes(self, old_nome, old_descricao, old_preco_de_custo, old_preco, old_categoria, old_marca, old_cor, old_quantidade, old_imagem_principal, old_especificacao):
        alteracoes = []

        if old_nome != self.nome:
            alteracoes.append(f"Nome alterado de '{old_nome}' para '{self.nome}'")

        if old_descricao.strip() != self.descricao.strip():
            alteracoes.append("Descrição alterada")

        if old_preco_de_custo != self.preco_de_custo:
            alteracoes.append(f"Preço de custo alterado de '{old_preco_de_custo}' para '{self.preco_de_custo}'")

        if old_preco != self.preco:
            alteracoes.append(f"Preço alterado de '{old_preco}' para '{self.preco}'")

        if old_categoria != self.categoria:
            alteracoes.append(f"Categoria alterada de '{old_categoria}' para '{self.categoria}'")

        if old_marca != self.marca:
            alteracoes.append(f"Marca alterada de '{old_marca}' para '{self.marca}'")

        if old_cor != self.cor:
            alteracoes.append(f"Cor alterada de '{old_cor}' para '{self.cor}'")

        if old_quantidade != int(self.quantidade):
            alteracoes.append(f"Quantidade alterada de '{old_quantidade}' para '{self.quantidade}'")

        if old_imagem_principal != self.imagem_principal:
            alteracoes.append(f"Imagem principal alterada de '{old_imagem_principal}' para '{self.imagem_principal}'")

        if old_especificacao != self.especificacao:
            alteracoes.append(f"As especificações foram alteradas")


        return ", ".join(alteracoes)
    
class Imagens(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE) 
    foto = models.ImageField(upload_to ='produtos/')

    def __str__(self):
        return f"{self.foto}"
    
class Avaliacao(models.Model):
    choices = (
        ('1', 'Pessimo'),
        ('2', 'Ruim'),
        ('3', 'Bom'),
        ('4', 'Otimo'),
        ('5', 'Perfeito')
    )
    usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE)
    estrelas = models.CharField(max_length=1, choices=choices)
    comentario = models.TextField(blank=True, null=True)
    data_avaliacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return f"{self.produto} - {self.usuario.nome} - {self.data_atualizacao}"
    
class DestacadosHome(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE)

    def __str__(self):
        return self.produto.nome
    

class RegistroAlteracaoProduto(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.SET_NULL, null=True)
    data_atualizacao = models.DateTimeField(default=timezone.now)
    detalhes = models.TextField()

    def __str__(self):
        return f"{self.produto.nome} - {self.data_atualizacao}"

produtos/forms.py
from dataclasses import fields
from django import forms
from .models import Categoria
from django.forms.widgets import ClearableFileInput
from ckeditor_uploader.fields import RichTextUploadingFormField

class CadastrarProduto(forms.Form):
    nome = forms.CharField(max_length=40)
    descricao = forms.CharField(max_length=100000, required=False)
    preco_de_custo = forms.CharField(max_length=11)
    preco = forms.CharField(max_length=11)
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all(), required=False)
    marca = forms.CharField(max_length=50, required=False)
    cor = forms.CharField(max_length=30, required=False) 
    quantidade = forms.IntegerField()
    imagem_principal = forms.ImageField(required=False)
    outras_imagens = forms.ImageField(widget=ClearableFileInput(attrs={'multiple':True}), required=False)
    especificacao = RichTextUploadingFormField(required=False)
    frete_gratis = forms.BooleanField(required=False)
    altura = forms.CharField(max_length=10, required=False)
    largura = forms.CharField(max_length=10, required=False)
    profundidade = forms.CharField(max_length=10, required=False)
    peso = forms.CharField(max_length=10, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['descricao'].widget = forms.Textarea()

class AtualizarEspecificacao(forms.Form):
    especificacao = RichTextUploadingFormField()

produtos/templates/alterar_produto.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'produtos/css/alterar_produto.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

    <div class="row">
        <div class="col-md-3">
          {% if produto.imagem_principal %}
          <img width="100%" src="{{produto.imagem_principal.url}}">
      {% else %}
          <img width="100%" src="{% static 'produtos\img\sem foto.jpg' %}">
      {% endif %}
        </div>
    </div>

    <br> 
    CADASTRADO EM: {{produto.data_cadastro|date:"d/m/Y" }} às {{ produto.data_cadastro|time:"H:i" }}
    <br>
    ATUALIZADO EM: {{produto.data_atualizacao|date:"d/m/Y" }} às {{ produto.data_atualizacao|time:"H:i" }}

    <div class="container">
        <br>
      <form action="{% url 'alterar_produto' produto.id %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}

            <label>Nome do produto:</label>
            <input style="width: 40%;" class="form-control" type="text" maxlength="40" value="{{produto.nome}}" name="nome">
          </p>

          <label for="campo_descricao">Descricao:</label>
          <textarea id="campo_descricao" name="descricao" rows="4" cols="50">
            {{produto.descricao}}
          </textarea>

          <p> 
            <label for="preco_de_custo">Preço de Custo:</label>
            <input style="width: 40%;" class="form-control" id="preco_de_custo" type="text"  value="{{produto.preco_de_custo}}" name="preco_de_custo">
          </p>
  
          <p> 
            <label>Preço:</label>
            <input style="width: 40%;" class="form-control" id="preco" type="text"  value="{{produto.preco}}" name="preco">
          </p>
  
          <label>Categoria:</label>
          <select style="width: 20%;" class="form-control" name="categoria">
            <option value=''>Escolha uma categoria:</option>
            <option value=''>Sem categoria:</option>
            {% for categoria in categorias %}
              {% if produto.categoria.nome == categoria.nome %}
                <option value="{{categoria.id}}" selected>{{categoria}}</option>
              {% else %}
                <option value="{{categoria.id}}">{{categoria}}</option>
              {% endif %}
            {% endfor %}
          </select>
        <br>

        <p> 
          <label>Marca:</label>
          <input style="width: 40%;" class="form-control" type="text"  value="{{produto.marca}}" name="marca" maxlength="50">
        </p>

        <p> 
          <label>Cor:</label>
          <input style="width: 40%;" class="form-control" type="text"  value="{{produto.cor}}" name="cor" maxlength="30">
        </p>

        <p> 
          <label>Quantidade:</label>
          <input style="width: 40%;" class="form-control" type="number"  value="{{produto.quantidade}}" name="quantidade">
        </p>

        <label>Frete Grátis:</label>
          <select style="width: 20%;" class="form-control" name="frete_gratis">
            {% if produto.frete_gratis %}
              <option value="sim" selected>Sim</option>
              <option value="nao">Não</option>
            {% else %}
              <option value="nao" selected>Não</option>
              <option value="sim">Sim</option>
            {% endif %}
          </select>
        <br>

        <p> 
          <label>Altura:</label>
          <input style="width: 40%;" class="form-control" id="altura" type="text"  value="{{produto.altura}}" name="altura">
        </p>

        <p> 
          <label>Largura:</label>
          <input style="width: 40%;" class="form-control" id="largura" type="text"  value="{{produto.largura}}" name="largura">
        </p>

        <p> 
          <label>Profundidade:</label>
          <input style="width: 40%;" class="form-control" id="profundidade" type="text"  value="{{produto.profundidade}}" name="profundidade">
        </p>

        <p> 
          <label>Peso:</label>
          <input style="width: 40%;" class="form-control" id="peso" type="text"  value="{{produto.peso}}" name="peso">
        </p>


        <input type="submit" class="btn btn-success btn-lg" value="Alterar">

        </form>
    </div> 

    <br>
    <br>
    <br>

    <div class="container">
      <form action="{% url 'atualizar_especificacao' produto.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form_especificacao.media}}
        {{form_especificacao.as_table}}
        <input type="submit" class="btn btn-success btn-lg" value="Alterar">
      </form>
    </div> 

    <br>
    <br>
    <br>

  <div>
    Alteração de imagens:
    <form action="{% url 'alterar_imagem_principal' produto.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <p>
        <label>Imagem principal:</label>
      <input type="file" name="imagem_principal">
      </p>
      <input type="submit" class="btn btn-success btn-lg" value="Alterar">
    </form>

    <br>

    <form action="{% url 'incluir_imagens' produto.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <p>
        <label>Incluir outras imagens:</label>
      <input type="file" name="imagens" multiple>
      </p>
      <input type="submit" class="btn btn-success btn-lg" value="Incluir">
    </form>

  </div>
  
  <br>
  <br>

{% if produto.imagem_principal %}
  <div class="row">
    <p>Excluir imagens:</p>
    <div class="col-md">
      <div class="card" style="width: 18rem;">
          <div class="card-body">
              <img width="100%" src="{{produto.imagem_principal.url}}">
              <a class="btn btn-danger" href="{% url 'excluir_imagem_principal' produto.id %}" role="button">Excluir</a>
          </div>
        </div>
    </div>
  </div>
  {% endif %}

<br>
<br>
{% if imagens %}
  <div class="row">
    <div class="col-md">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          {% for img in imagens %}
            <img width="100%" src="{{img.foto.url}}">
            <a class="btn btn-danger" href="{% url 'excluir_imagem' img.id produto.id %}" role="button">Excluir</a>
            <br>
            <br>
            <br>
          {% endfor %}
        </div>
      </div>
    </div>
  </div> 
{% endif %} 

{% endblock %} 

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    
    <script> 
        $(document).ready(function(){
          $('#preco_de_custo').mask('000000,00', {reverse: true});
          $('#preco').mask('000000,00', {reverse: true});
          $('#altura').mask('000,00', {reverse: true});
          $('#largura').mask('000,00', {reverse: true});
          $('#profundidade').mask('000,00', {reverse: true});
          $('#peso').mask('000,00', {reverse: true});

        });

    </script>
{% endblock %}

produtos/templates/cadastrar_produto.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'produtos/css/cadastrar_produto.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

    <form action="{% url 'cadastrar_produto' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <table>
        {{form.media}}
        {{form.as_table}}
        {% if form.errors %}
          {% for field in form %}
              {% for error in field.errors %}
                  <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
        {% endif %}
      </table>
      
      <input class="btn btn-success" type="submit" value="Enviar">
    </form>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    
    <script> 
        $(document).ready(function(){
          $('#id_preco_de_custo').mask('000000,00', {reverse: true});
          $('#id_preco').mask('000000,00', {reverse: true});
          $('#id_altura').mask('000,00', {reverse: true});
          $('#id_largura').mask('000,00', {reverse: true});
          $('#id_profundidade').mask('000,00', {reverse: true});
          $('#id_peso').mask('000,00', {reverse: true});

        });

    </script>
{% endblock %}

produtos/templates/listar_categorias.html
{% extends 'base.html' %}
{% load static %}
{% load filtros %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'produtos/css/listar_categorias.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}
    <div class="container-fluid d-sm-flex align-items-stretch px-0">
        {% include "menu_gerente.html" %}
      
        <div class="container px-5 py-4">
            <div class="text-center mt-1">
                <h2>Categorias</h2>
            </div>

            <div class="m-3 d-flex justify-content-center">
                <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#cadastroModal">Cadastrar +</button>
            </div>
            <div class="modal fade" id="cadastroModal" tabindex="-1" aria-labelledby="cadastroModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="cadastroModalLabel" style="margin-left:80px">Cadastrar nova categoria</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                    </div>
                    <div class="modal-body">
                    <form action="{% url 'cadastrar_categoria' %}" method="POST">
                        {% csrf_token %}
                        <input type="text" class="form-control" name="nome" maxlength="40">
                        <div class="d-flex justify-content-center">
                            <input type="submit" value="SALVAR" class="btn my-2">
                        </div>
                    </form>
                    </div>
                  </div>
                </div>
            </div>

            <div class="my-3 d-flex justify-content-center">
                <form class="input-group" action="#" method="GET" style="width:70%"> {% csrf_token %} 
                    <input type="text" placeholder="Busque pelo nome" class="form-control" name="nome">
                    <button class = "btn"  type = "submit"><i class = "fa fa-search"></i></button>
                </form>
            </div>
    
            <div class="table-responsive">
                <table class="table table-striped border">
                <thead>
                    <tr>
                    <th scope="col">Nome</th>
                    <th class="pe-2 text-end" scope="col">Excluir</th>
                    </tr>
                </thead>
                <tbody>
                    {% for categoria in categorias %}
                        <tr> 
                        <td>{{categoria.nome}}</td> 
                        <td class="pe-3 text-end"><a href="{% url 'excluir_categoria' categoria.id %}" class="lixeira"><i class="fas fa-trash fa-lg"></i></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
    
            <div class="pagination">
                {% if categorias.has_previous %}
                <a class="pagination-action" href="?{% param_replace page=1 %}">
                    <i class='fa fa-angle-double-left' aria-hidden="true"></i> </a>
                <a class="pagination-action" href="?{% param_replace page=categorias.previous_page_number %}">
                    <i class='fa fa-arrow-left' aria-hidden="true"></i>
                </a>
                {% endif %}
                {% for num in categorias.paginator.page_range %}
                    {% if categorias.number == num %}
                        <span class="pagination-number pagination-current">{{ num }}</span>
                    {% elif num > categorias.number|add:'-3' and num < categorias.number|add:'3' %}
                        <a class="pagination-number" href="?{% param_replace page=num %}">{{ num }}</a>
                    {% endif %}
                {% endfor %}
                {% if categorias.has_next %}
                    <a class="pagination-action" href="?{% param_replace page=categorias.next_page_number %}">
                        <i class='fa fa-arrow-right' aria-hidden="true"></i>
                    </a>
                    <a class="pagination-action" href="?{% param_replace page=categorias.paginator.num_pages %}" >        
                        <i class='fa fa-angle-double-right' aria-hidden="true"></i>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}