gestao/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('criar_gerente/', views.criar_gerente, name="criar_gerente"),
    path('salvar_gerente/', views.salvar_gerente, name='salvar_gerente'),
    path('adm_estoque/', views.adm_estoque, name='adm_estoque'),
    path('detalhes_produto/<int:id>', views.detalhes_produto, name='detalhes_produto'),
    path('painel_controle/', views.painel_controle, name='painel_controle'),
    path('produtos_home/', views.produtos_home, name='produtos_home'),
    path('exibicao_home/', views.exibicao_home, name='exibicao_home'),
    path('gerenciar_banners/', views.gerenciar_banners, name='gerenciar_banners'),
    path('adicionar_banner/', views.adicionar_banner, name='adicionar_banner'),
    path('selecionar_banner/<int:id_banner>', views.selecionar_banner, name='selecionar_banner'),
    path('deletar_banner/<int:id_banner>', views.deletar_banner, name='deletar_banner'),
    path('tirar_banner_home/<int:id_banner>', views.tirar_banner_home, name='tirar_banner_home'),
    path('gerenciar_cupons/', views.gerenciar_cupons, name='gerenciar_cupons'),
    path('alterar_cupons/', views.alterar_cupons, name='alterar_cupons'),
    path('consultar_pedidos/', views.consultar_pedidos, name='consultar_pedidos'),
    
   
]

pytudo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views as ckeditor_views
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('usuarios/', include('usuarios.urls')),
    path('produtos/', include('produtos.urls')),
    path('accounts/', include('allauth.urls')),
    path('gestao/', include('gestao.urls')),
    path('vendas/', include('vendas.urls')),
    path('checkout/', include('checkout.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('info_adicional_usuario/', views.info_adicional_usuario, name="info_adicional_usuario"),
    path('listar_usuarios/', views.listar_usuarios, name='listar_usuarios'),
    path('excluir_usuario/<int:id>', views.excluir_usuario, name='excluir_usuario'),
    path('ver_usuario/<int:id>', views.ver_usuario, name='ver_usuario'),
    path('atualizar_usuario/<int:id>', views.atualizar_usuario, name='atualizar_usuario'),
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    path('usuario_atualiza_cadastro/', views.usuario_atualiza_cadastro, name='usuario_atualiza_cadastro'),
    path('alteracoes_usuario/', views.alteracoes_usuario, name='alteracoes_usuario'),
    path('meus_pedidos/', views.meus_pedidos, name='meus_pedidos'),
    path('ver_pedido/<int:id>', views.ver_pedido, name='ver_pedido'),
]

usuarios/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from cpf_field.models import CPFField
from django.utils import timezone

class Usuarios(models.Model):
    ESTADOS_BRASILEIROS = (
        ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
    )

    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nome = models.CharField(max_length=40)
    cpf = CPFField('CPF')
    data_de_nascimento = models.DateField() 
    celular = PhoneNumberField(null=False, blank=False)
    endereco = models.CharField(max_length=50)
    numero_endereco = models.CharField(max_length=10)
    complemento = models.CharField(max_length=50, blank=True, null= True)
    bairro = models.CharField(max_length=30)
    cidade = models.CharField(max_length=30)
    estado = models.CharField(max_length=2, choices=ESTADOS_BRASILEIROS)
    data_atualizacao = models.DateTimeField(auto_now=True, null=True) 


    def __str__(self):
        return str(self.usuario)
    
    def delete(self, *args, **kwargs):
        registro = RegistroAlteracaoUsuario(
            usuario=self,
            detalhes=f'Usuario {self.nome} excluído.',
        )
        registro.save()
        super().delete(*args, **kwargs)
        
    
    def save(self, *args, **kwargs):
        is_new = self._state.adding
        if not is_new:
            old_obj = Usuarios.objects.get(pk=self.pk)
            old_nome = old_obj.nome
            old_cpf = old_obj.cpf
            old_data_de_nascimento = old_obj.data_de_nascimento
            old_celular = old_obj.celular
            old_endereco = old_obj.endereco
            old_numero_endereco = old_obj.numero_endereco
            old_complemento = old_obj.complemento
            old_bairro = old_obj.bairro
            old_cidade = old_obj.cidade
            old_estado = old_obj.estado
            detalhes = f"Usuario atualizado - {self.comparar_alteracoes_usuario(old_nome, old_cpf, old_data_de_nascimento, old_celular, old_endereco, old_numero_endereco, old_complemento, old_bairro, old_cidade, old_estado)}"
        else:
            detalhes = f"Usuario {self.nome} completou seu perfil"

        super().save(*args, **kwargs)
            
        registro = RegistroAlteracaoUsuario(
            usuario=self,
            detalhes=detalhes,
        )
        registro.save()

    def comparar_alteracoes_usuario(self, old_nome, old_cpf, old_data_de_nascimento, old_celular, old_endereco, old_numero_endereco, old_complemento, old_bairro, old_cidade, old_estado):
        alteracoes = []

        if old_nome != self.nome:
            alteracoes.append(f"Nome alterado de '{old_nome}' para '{self.nome}'")

        if old_cpf != self.cpf:
            alteracoes.append(f"CPF alterado de '{old_cpf}' para '{self.cpf}'")

        if old_data_de_nascimento != self.data_de_nascimento.date():
            alteracoes.append(f"Data de nascimento alterada de '{old_data_de_nascimento}' para '{self.data_de_nascimento.date()}'")

        if old_celular != self.celular:
            alteracoes.append(f"Celular alterado de '{old_celular}' para '{self.celular}'")

        if old_endereco != self.endereco:
            alteracoes.append(f"Endereço alterado de '{old_endereco}' para '{self.endereco}'")

        if old_numero_endereco != self.numero_endereco:
            alteracoes.append(f"Número de endereço alterado de '{old_numero_endereco}' para '{self.numero_endereco}'")

        if old_complemento != self.complemento:
            if old_complemento == '' or self.complemento == '':
                alteracoes.append(f"Complemento alterado para '{self.complemento}'")
            else:
                alteracoes.append(f"Complemento alterado de '{old_complemento}' para '{self.complemento}'")

        if old_bairro != self.bairro:
            alteracoes.append(f"Bairro alterado de '{old_bairro}' para '{self.bairro}'")

        if old_cidade != self.cidade:
            alteracoes.append(f"Cidade alterada de '{old_cidade}' para '{self.cidade}'")

        if old_estado != self.estado:
            alteracoes.append(f"Estado alterado de '{old_estado}' para '{self.estado}'")

        return ", ".join(alteracoes)
    
class RegistroAlteracaoUsuario(models.Model):
    usuario = models.ForeignKey(Usuarios, on_delete=models.SET_NULL, null=True)
    data_atualizacao = models.DateTimeField(default=timezone.now)
    detalhes = models.TextField()

    def __str__(self):
        return f"{self.usuario.nome} - {self.data_atualizacao}"


    
    

   

usuarios/forms.py
from dataclasses import fields
from django import forms
from .models import Usuarios
from phonenumber_field.formfields import PhoneNumberField

class CadastroUsuario(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['usuario'].widget = forms.HiddenInput()

class AtualizarUsuario(forms.Form):
    nome = forms.CharField(max_length=40)
    cpf = forms.CharField(max_length=14)
    data_de_nascimento = forms.DateField()
    celular = PhoneNumberField()
    endereco = forms.CharField(max_length=50)
    numero_endereco = forms.CharField(max_length=10)
    complemento = forms.CharField(max_length=50, required=False)
    bairro = forms.CharField(max_length=30)
    cidade = forms.CharField(max_length=30)
    estado = forms.ChoiceField(choices=Usuarios.ESTADOS_BRASILEIROS, label='Estado')



        
    


    
    

usuarios/templates/alteracoes_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'usuarios/css/perfil_usuario.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<div class="container-fluid d-sm-flex align-items-stretch px-0">
  {% include "menu_usuario.html" %}
  
  <div class="container p-4">
    <div class="text-center mt-1">
      <h2>Histórico de Alterações:</h2>
    </div>
    <div class="table-responsive">
      <table class="table">
        <tr>
          <th>Data</th>
          <th>Hora</th>
          <th>Informação</th>
        </tr>
        <tr>
          <td>{{usuario.usuario.date_joined|date:"d/m/Y" }}</td>
          <td>{{ usuario.usuario.date_joined|time:"H:i" }}</td>
          <td>Conta criada</td>
        </tr>
        {% for registro in registros %}
        <tr>
          <td>{{registro.data_atualizacao|date:"d/m/Y"}}</td>
          <td>{{registro.data_atualizacao|time:"H:i"}}</td>
          <td>{{registro.detalhes}}</td>
        </tr>
        {% endfor %}
      </table>
    </div> 
    <p><b>DATA DO ULTIMO LOGIN:</b> {{usuario.usuario.last_login|date:"d/m/Y" }} às {{ usuario.usuario.last_login|time:"H:i" }}</p>
  </div>
</div>


{% endblock %} 

usuarios/templates/atualizar_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'usuarios/css/info_adicional_usuario.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

    <div class="text-center mt-5">
        <h2>Atualizar Cadastro:</h2>
    </div>
    <div class="container d-flex justify-content-center my-3">
        <form action="{% url 'atualizar_usuario' usuario.id %}" class="cadastro p-3 border" method="POST">{% csrf_token %}
            {{form.as_p}}
            {{ form.non_field_errors }}
            <div class="text-center my-3">
                <button class="btn px-5" type="submit">Enviar</button>
            </div>
        </form>
    </div>
    
    <div class="text-center my-2">
        ATUALIZADO ULTIMA VEZ EM: {{usuario.data_atualizacao|date:"d/m/Y" }} às {{usuario.data_atualizacao|time:"H:i" }}
    </div>
    

{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    
    <script> 
        $(document).ready(function(){
            $('#id_cpf').mask('000.000.000-00', {reverse: true});
            $('#id_data_de_nascimento').mask('00/00/0000');
            var SPMaskBehavior = function (val) {
                return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
              },
              spOptions = {
                onKeyPress: function(val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                  }
              };
              
              $('#id_celular').mask(SPMaskBehavior, spOptions);

        });

    </script>
{% endblock %}

usuarios/templates/info_adicional_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'usuarios/css/info_adicional_usuario.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}
    <div class="text-center mt-5">
        <h2>Cadastro:</h2>
    </div>
    <div class="container d-flex justify-content-center my-3">
        <form action="{% url 'info_adicional_usuario' %}" class="cadastro p-3 border" method="POST">{% csrf_token %}
            {{form.as_p}}
            {{ form.non_field_errors }}
            <div class="text-center my-3">
                <button class="btn px-5" type="submit">Enviar</button>
            </div>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    
    <script> 
        $(document).ready(function(){
            $('#id_cpf').mask('000.000.000-00', {reverse: true});
            $('#id_data_de_nascimento').mask('00/00/0000');
            var SPMaskBehavior = function (val) {
                return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
              },
              spOptions = {
                onKeyPress: function(val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                  }
              };
              
              $('#id_celular').mask(SPMaskBehavior, spOptions);

        });

    </script>
{% endblock %}
    


    

usuarios/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'usuarios/css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

    {% if messages %}
        {% for message in messages %}
            <section class="alert {{message.tags}}">
                {{message}}
            </section>
        {% endfor %}
    {% endif %}

    <div class="wrapper">
        <form action="{% url 'cadastrar_usuario' %}" method="POST">{% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input class="btn btn-success" type="submit" value="Enviar">
        </form>
    </div>

{% endblock %}

usuarios/templates/menu_usuario.html
<nav class="sidebar bg-dark">
    <div class="p-4">
      <h1 class="m-0 text-white">Menu</h1>
      <hr class="mt-0 mb-4 text-white">
      <ul class="list-unstyled mb-2">
      <li class="my-3">
      <a href="{% url 'perfil_usuario' %}"><span class="fa fa-user mr-3"></span> Perfil</a>
      </li>
      <li class="my-3">
      <a href="{% url 'meus_pedidos' %}"><span class="fa fa-envelope mr-3"></span> Meus pedidos</a>
      </li>
        <li class="my-3">
        <a href="{% url 'ver_lista_desejo' %}"><span class="fa fa-heart mr-3"></span> Lista de Desejos </a>
        </li>
      <li class="my-3">
      <a href="{% url 'usuario_atualiza_cadastro' %}"><span class="fa fa-spinner mr-3"></span> Atualizar Cadastro</a>
      </li>
      <li class="my-3">
      <a href="{% url 'alteracoes_usuario' %}"><span class="fa fa-history mr-3"></span> Histórico de Alterações</a>
      </li>
      <li class="my-3">
      <a href="{% url 'account_logout' %}"><span class="fa fa-power-off mr-3"></span> Sair</a>
      </li>
      </ul>
    </div>
    </nav>

usuarios/templates/meus_pedidos.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
  <link href="{% static 'usuarios/css/perfil_usuario.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<div class="container-fluid d-sm-flex align-items-stretch px-0">
  {% include "menu_usuario.html" %}
  
  <div class="container px-5 py-4">
    <div class="table-responsive">
      <table class="table table-striped border">
        <thead>
          <tr>
            <th scope="col">Número</th>
            <th scope="col">Data</th>
            <th scope="col">Valor</th>
            <th scope="col">Pagamento</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
        {% for pedido in pedidos %}
          <tr onclick="window.location='{% url 'ver_pedido' pedido.id %}'" style="cursor: pointer;">
            <td>{{pedido.id}}</td>
            <td>{{pedido.data_pedido|date:"d/m/Y"}}</td>
            <td>{{pedido.valor_total}}</td>
            <td>{{pedido.metodo_de_pagamento}}</td>
            <td>{{pedido.status}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </div>
</div>


{% endblock %} 

usuarios/templates/perfil_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'usuarios/css/perfil_usuario.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<div class="container-fluid d-sm-flex align-items-stretch px-0">
  {% include "menu_usuario.html" %}
  
  <div class="container px-5 py-4">
    <div class="table-responsive">
      <table class="table">
          <tr>
            <td class="fw-bold">Nome</td>
            <td>{{usuario.nome}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Usuário</td>
            <td>{{usuario.usuario}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Celular</td>
            <td>{{usuario.celular.as_national}}</td>
          </tr>
          <tr>
            <td class="fw-bold">CPF</td>
            <td>{{usuario.cpf}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Data de Nascimento</td>
            <td>{{usuario.data_de_nascimento|date:"d/m/Y"}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Endereço</td>
            <td>{{usuario.endereco}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Número</td>
            <td>{{usuario.numero_endereco}}</td>
          </tr>
          {% if usuario.complemento %}
          <tr>
            <td class="fw-bold">Complemento</td>
            <td>{{usuario.complemento}}</td>
          </tr>
          {% endif %}
          <tr>
            <td class="fw-bold">Bairro</td>
            <td>{{usuario.bairro}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Cidade</td>
            <td>{{usuario.cidade}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Estado</td>
            <td>{{usuario.get_estado_display}}</td>
          </tr>
      </table>
  </div>
  </div>
</div>


{% endblock %} 

usuarios/templates/usuario_atualiza_cadastro.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
    <link href="{% static 'usuarios/css/perfil_usuario.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<div class="container-fluid d-sm-flex align-items-stretch px-0">
  {% include "menu_usuario.html" %}
  
  <div class="p-4 w-100">
    <div class="text-center mt-1">
        <h2>Atualizar Cadastro:</h2>
    </div>
    <div class="container d-flex justify-content-center my-3">
        <form action="{% url 'usuario_atualiza_cadastro' %}" class="cadastro p-3 border" method="POST">{% csrf_token %}
            {{form.as_p}}
            {{ form.non_field_errors }}
            <div class="text-center my-3">
                <button class="btn px-5" type="submit">Enviar</button>
            </div>
        </form>
    </div>
    
  </div>
</div>

{% endblock %} 

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    
    <script> 
        $(document).ready(function(){
            $('#id_cpf').mask('000.000.000-00', {reverse: true});
            $('#id_data_de_nascimento').mask('00/00/0000');
            var SPMaskBehavior = function (val) {
                return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
              },
              spOptions = {
                onKeyPress: function(val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                  }
              };
              
              $('#id_celular').mask(SPMaskBehavior, spOptions);

        });

    </script>
{% endblock %}

usuarios/templates/ver_pedido.html
{% extends 'base.html' %}
{% load static %}
{% load permission_tags %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 
  <link href="{% static 'usuarios/css/perfil_usuario.css' %}" rel="stylesheet">
{% endblock %}

{% block 'body' %}

<div class="container-fluid d-sm-flex align-items-stretch px-0">
  {% if request.user|has_role:"gerente" %}
    {% include "menu_gerente.html" %}
  {% else %}
    {% include "menu_usuario.html" %}
  {% endif %}
  
  <div class="container px-5 py-4">
    <div class="table-responsive border">
      <table class="table">
        <tr>
          <td class="fw-bold">Número do Pedido</td>
          <td>{{pedido.id}}</td>
        </tr>
        <tr>
          <td class="fw-bold">Usuario</td>
          <td>{{pedido.usuario.nome}}</td>
        </tr>
        <tr>
          <td class="fw-bold">Data da Compra</td>
          <td>{{pedido.data_pedido|date:"d/m/Y"}} às {{pedido.data_pedido|time:"H:i"}}</td>
        </tr>
        <tr>
          <td class="fw-bold">Valor Total</td>
          <td>R$ {{pedido.valor_total}}</td>
        </tr>
        <tr>
          <td class="fw-bold">Metodo de Pagamento</td>
          <td>{{pedido.metodo_de_pagamento}}</td>
        </tr>
        <tr>
          <td class="fw-bold">Quantidade de Parcelas</td>
          <td>{{pedido.parcelas}}</td>
        </tr>
        <tr>
          <td class="fw-bold">Status do Pagamento</td>
          <td>{{pedido.status}}</td>
        </tr>
        <tr>
          <td class="fw-bold">Data da última atualização</td>
          <td>{{pedido.data_ultima_atualizacao_pedido|date:"d/m/Y"}} às {{pedido.data_ultima_atualizacao_pedido|time:"H:i"}}</td>
        </tr>
     </table>
   </div>
    
    <div class="table-responsive">
      <table class="table table-striped border">
        <thead>
          <tr>
            <th scope="col">Produto</th>
            <th scope="col">Quantidade</th>
          </tr>
        </thead>

        <tbody>
          {% for item in itens %}
          <tr>
            <td>{{item.produto}}</td>
            <td>{{item.quantidade}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if pedido.mensagem_de_erro %}
      <div class="container my-3">
        <p><b>Erro do pedido:</b></p>
        {{pedido.mensagem_de_erro}}
      </div>
    {% endif %}

    {% if pedido.link_pagamento %}
      <div class="container my-3 text-center">
        <p><b>Clique no botão para pagar:</b></p>
        <a href={{pedido.link_pagamento}} target="_blank" rel="noopener noreferrer">
          <button class="btn">Pagar</button>
        </a>
      </div>
    {% endif %}
  </div>
</div>


{% endblock %} 

usuarios/templates/ver_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}PYTudo{% endblock %}

{% block 'head' %} 

{% endblock %}

{% block 'body' %}

<div class="container p-5 my-5 border">
    <h2 class="text-center mb-4">Perfil do Usuário:</h2>
    <div class="table-responsive">
      <table class="table">
          
          <tr>
            <td class="fw-bold">Nome</td>
            <td>{{usuario.nome}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Usuário</td>
            <td>{{usuario.usuario}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Celular</td>
            <td>{{usuario.celular.as_national}}</td>
          </tr>
          <tr>
            <td class="fw-bold">CPF</td>
            <td>{{usuario.cpf}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Data de Nascimento</td>
            <td>{{usuario.data_de_nascimento|date:"d/m/Y"}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Endereço</td>
            <td>{{usuario.endereco}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Número</td>
            <td>{{usuario.numero_endereco}}</td>
          </tr>
          {% if usuario.complemento %}
          <tr>
            <td class="fw-bold">Complemento</td>
            <td>{{usuario.complemento}}</td>
          </tr>
          {% endif %}
          <tr>
            <td class="fw-bold">Bairro</td>
            <td>{{usuario.bairro}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Cidade</td>
            <td>{{usuario.cidade}}</td>
          </tr>
          <tr>
            <td class="fw-bold">Estado</td>
            <td>{{usuario.get_estado_display}}</td>
          </tr>
      </table>
    </div>
</div>

<div class="container p-5 mb-5 border">
  <h2 class="text-center mb-4">Histórico de Pedidos:</h2>
  <div class="table-responsive">
    <table class="table table-striped border">
      <thead>
        <tr>
          <th scope="col">Número</th>
          <th scope="col">Data</th>
          <th scope="col">Valor</th>
          <th scope="col">Pagamento</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        {% for pedido in pedidos %}
          <tr onclick="window.location='{% url 'ver_pedido' pedido.id %}'" style="cursor: pointer;">
            <td>{{pedido.id}}</td>
            <td>{{pedido.data_pedido|date:"d/m/Y"}}</td>
            <td>{{pedido.valor_total}}</td>
            <td>{{pedido.metodo_de_pagamento}}</td>
            <td>{{pedido.status}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
    
<div class="container p-5 mb-5 border">
    <h2 class="text-center mb-4">Histórico de Alterações:</h2>
    <div class="table-responsive">
      <table class="table">
        <tr>
          <th>Data</th>
          <th>Hora</th>
          <th>Informação</th>
        </tr>
        <tr>
          <td>{{usuario.usuario.date_joined|date:"d/m/Y" }}</td>
          <td>{{ usuario.usuario.date_joined|time:"H:i" }}</td>
          <td>Conta criada</td>
        </tr>
        {% for registro in registros %}
        <tr>
          <td>{{registro.data_atualizacao|date:"d/m/Y"}}</td>
          <td>{{registro.data_atualizacao|time:"H:i"}}</td>
          <td>{{registro.detalhes}}</td>
        </tr>
        {% endfor %}
      </table>
    </div> 
    <p class="mt-3"><b>DATA DO ULTIMO LOGIN:</b> {{usuario.usuario.last_login|date:"d/m/Y" }} às {{ usuario.usuario.last_login|time:"H:i" }}</p>
  </div>
</div>


{% endblock %}